export const contasAPagarData = [
  {
    TipoOperacao: 'S',
    cod_empresa: 1,
    nm_empresa: 'Empresa Principal',
    desc_perfil_empresa: 'Matriz',
    cod_duplicata: 1001,
    cod_itens_duplicata: 1,
    acordo: 'N',
    tipo_nota: 'NFE',
    cod_venda: null,
    num_nota: '12345',
    n_documento: 'DOC-001',
    antecipacao: 'N',
    dev_troca: 'N',
    cod_saida_pgto: 1,
    cod_apropriacao: 10,
    desc_apropriacao: 'Despesas Administrativas',
    cod_grupo: 100,
    desc_grupo: 'Operacional',
    cod_sub_grupo: 1001,
    desc_sub_grupo: 'Energia',
    cod_conta: 50,
    desc_conta: 'Conta de Luz',
    desc_condpagto: '30 Dias',
    tipo_pagamento: 'Boleto',
    num_parc: 1,
    total_parc: 1,
    cod_pessoa: 500,
    nome_pessoa: 'Companhia de Energia Elétrica',
    tel_pessoa: '1199999999',
    email_financeiro: 'faturamento@energia.com',
    nm_funcionario: 'João',
    dt_emissao: '2023-10-01',
    dt_vencimento: '2023-10-15',
    dt_pagamento: '2023-10-14',
    data_baixa: '2023-10-14',
    dt_ultimo_pgto: '2023-10-14',
    vl_duplicata: 1500.0,
    vl_parcela: 1500.0,
    vl_desconto: 0,
    vl_juros: 0,
    vl_pago: 1500.0,
    pago: 'S',
    vl_frete: 0,
    vl_ipi: 0,
    vl_st: 0,
    lancamento: '123',
    layout_boleto: 'Padrão',
    nosso_numero: '987654321',
    obs_conta_pagar: 'Referente ao mês 10',
  },
  {
    TipoOperacao: 'S',
    cod_empresa: 1,
    nm_empresa: 'Empresa Principal',
    desc_perfil_empresa: 'Matriz',
    cod_duplicata: 1002,
    cod_itens_duplicata: 1,
    acordo: 'N',
    tipo_nota: 'NFE',
    cod_venda: null,
    num_nota: '12346',
    n_documento: 'DOC-002',
    antecipacao: 'N',
    dev_troca: 'N',
    cod_saida_pgto: 1,
    cod_apropriacao: 11,
    desc_apropriacao: 'Fornecedores',
    cod_grupo: 200,
    desc_grupo: 'Mercadorias',
    cod_sub_grupo: 2001,
    desc_sub_grupo: 'Iluminação',
    cod_conta: 51,
    desc_conta: 'Lâmpadas',
    desc_condpagto: '30 Dias',
    tipo_pagamento: 'Boleto',
    num_parc: 1,
    total_parc: 1,
    cod_pessoa: 501,
    nome_pessoa: 'Fornecedor de Iluminação SA',
    tel_pessoa: '1199999998',
    email_financeiro: 'faturamento@iluminacao.com',
    nm_funcionario: 'Maria',
    dt_emissao: '2023-10-05',
    dt_vencimento: '2023-11-05',
    dt_pagamento: null,
    data_baixa: null,
    dt_ultimo_pgto: null,
    vl_duplicata: 4500.0,
    vl_parcela: 4500.0,
    vl_desconto: 0,
    vl_juros: 0,
    vl_pago: 0,
    pago: 'N',
    vl_frete: 0,
    vl_ipi: 0,
    vl_st: 0,
    lancamento: '124',
    layout_boleto: 'Padrão',
    nosso_numero: '987654322',
    obs_conta_pagar: 'Estoque',
  },
  {
    TipoOperacao: 'S',
    cod_empresa: 1,
    nm_empresa: 'Empresa Principal',
    desc_perfil_empresa: 'Matriz',
    cod_duplicata: 1003,
    cod_itens_duplicata: 1,
    acordo: 'N',
    tipo_nota: 'NFE',
    cod_venda: null,
    num_nota: '12347',
    n_documento: 'DOC-003',
    antecipacao: 'N',
    dev_troca: 'N',
    cod_saida_pgto: 1,
    cod_apropriacao: 12,
    desc_apropriacao: 'Marketing',
    cod_grupo: 300,
    desc_grupo: 'Marketing',
    cod_sub_grupo: 3001,
    desc_sub_grupo: 'Agência',
    cod_conta: 52,
    desc_conta: 'Serviços',
    desc_condpagto: '15 Dias',
    tipo_pagamento: 'Pix',
    num_parc: 1,
    total_parc: 1,
    cod_pessoa: 502,
    nome_pessoa: 'Agência Criativa',
    tel_pessoa: '1199999997',
    email_financeiro: 'financeiro@agencia.com',
    nm_funcionario: 'Carlos',
    dt_emissao: '2023-10-10',
    dt_vencimento: '2023-10-25',
    dt_pagamento: null,
    data_baixa: null,
    dt_ultimo_pgto: null,
    vl_duplicata: 2000.0,
    vl_parcela: 2000.0,
    vl_desconto: 0,
    vl_juros: 0,
    vl_pago: 0,
    pago: 'N',
    vl_frete: 0,
    vl_ipi: 0,
    vl_st: 0,
    lancamento: '125',
    layout_boleto: 'Padrão',
    nosso_numero: '987654323',
    obs_conta_pagar: 'Campanha de Vendas',
  },
  {
    TipoOperacao: 'S',
    cod_empresa: 1,
    nm_empresa: 'Empresa Principal',
    desc_perfil_empresa: 'Matriz',
    cod_duplicata: 1004,
    cod_itens_duplicata: 1,
    acordo: 'N',
    tipo_nota: 'NFS',
    cod_venda: null,
    num_nota: '12348',
    n_documento: 'DOC-004',
    antecipacao: 'N',
    dev_troca: 'N',
    cod_saida_pgto: 1,
    cod_apropriacao: 10,
    desc_apropriacao: 'Despesas Administrativas',
    cod_grupo: 100,
    desc_grupo: 'Operacional',
    cod_sub_grupo: 1002,
    desc_sub_grupo: 'Aluguel',
    cod_conta: 53,
    desc_conta: 'Imóvel',
    desc_condpagto: 'Mensal',
    tipo_pagamento: 'Transferência',
    num_parc: 1,
    total_parc: 1,
    cod_pessoa: 503,
    nome_pessoa: 'Imobiliária Centro',
    tel_pessoa: '1199999996',
    email_financeiro: 'aluguel@imobiliaria.com',
    nm_funcionario: 'João',
    dt_emissao: '2023-10-01',
    dt_vencimento: '2023-10-10',
    dt_pagamento: '2023-10-09',
    data_baixa: '2023-10-09',
    dt_ultimo_pgto: '2023-10-09',
    vl_duplicata: 5000.0,
    vl_parcela: 5000.0,
    vl_desconto: 0,
    vl_juros: 0,
    vl_pago: 5000.0,
    pago: 'S',
    vl_frete: 0,
    vl_ipi: 0,
    vl_st: 0,
    lancamento: '126',
    layout_boleto: 'Padrão',
    nosso_numero: '987654324',
    obs_conta_pagar: 'Aluguel Matriz',
  },
  {
    TipoOperacao: 'S',
    cod_empresa: 1,
    nm_empresa: 'Empresa Principal',
    desc_perfil_empresa: 'Matriz',
    cod_duplicata: 1005,
    cod_itens_duplicata: 1,
    acordo: 'N',
    tipo_nota: 'NFE',
    cod_venda: null,
    num_nota: '12349',
    n_documento: 'DOC-005',
    antecipacao: 'N',
    dev_troca: 'N',
    cod_saida_pgto: 1,
    cod_apropriacao: 11,
    desc_apropriacao: 'Fornecedores',
    cod_grupo: 200,
    desc_grupo: 'Mercadorias',
    cod_sub_grupo: 2002,
    desc_sub_grupo: 'Fios e Cabos',
    cod_conta: 54,
    desc_conta: 'Cobre',
    desc_condpagto: '60 Dias',
    tipo_pagamento: 'Boleto',
    num_parc: 1,
    total_parc: 1,
    cod_pessoa: 504,
    nome_pessoa: 'Indústria de Cabos SA',
    tel_pessoa: '1199999995',
    email_financeiro: 'faturamento@cabos.com',
    nm_funcionario: 'Maria',
    dt_emissao: '2023-09-15',
    dt_vencimento: '2023-11-15',
    dt_pagamento: null,
    data_baixa: null,
    dt_ultimo_pgto: null,
    vl_duplicata: 12000.0,
    vl_parcela: 12000.0,
    vl_desconto: 0,
    vl_juros: 0,
    vl_pago: 0,
    pago: 'N',
    vl_frete: 0,
    vl_ipi: 0,
    vl_st: 0,
    lancamento: '127',
    layout_boleto: 'Padrão',
    nosso_numero: '987654325',
    obs_conta_pagar: 'Reposição de Estoque',
  },
  {
    TipoOperacao: 'S',
    cod_empresa: 1,
    nm_empresa: 'Empresa Principal',
    desc_perfil_empresa: 'Matriz',
    cod_duplicata: 1006,
    cod_itens_duplicata: 1,
    acordo: 'N',
    tipo_nota: 'NFE',
    cod_venda: null,
    num_nota: '12350',
    n_documento: 'DOC-006',
    antecipacao: 'N',
    dev_troca: 'N',
    cod_saida_pgto: 1,
    cod_apropriacao: 10,
    desc_apropriacao: 'Despesas Administrativas',
    cod_grupo: 100,
    desc_grupo: 'Operacional',
    cod_sub_grupo: 1003,
    desc_sub_grupo: 'Internet',
    cod_conta: 55,
    desc_conta: 'Telecomunicações',
    desc_condpagto: '30 Dias',
    tipo_pagamento: 'Débito em Conta',
    num_parc: 1,
    total_parc: 1,
    cod_pessoa: 505,
    nome_pessoa: 'Provedor de Internet Ltda',
    tel_pessoa: '1199999994',
    email_financeiro: 'cobranca@provedor.com',
    nm_funcionario: 'João',
    dt_emissao: '2023-10-05',
    dt_vencimento: '2023-10-05',
    dt_pagamento: '2023-10-05',
    data_baixa: '2023-10-05',
    dt_ultimo_pgto: '2023-10-05',
    vl_duplicata: 350.0,
    vl_parcela: 350.0,
    vl_desconto: 0,
    vl_juros: 0,
    vl_pago: 350.0,
    pago: 'S',
    vl_frete: 0,
    vl_ipi: 0,
    vl_st: 0,
    lancamento: '128',
    layout_boleto: 'Padrão',
    nosso_numero: '987654326',
    obs_conta_pagar: 'Mensalidade',
  },
]
